INSERT INTO cat_sat_regimen_fiscal VALUES(1,'601','General de Ley Personas Morales', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(2,'603','Personas Morales con Fines no Lucrativos', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(3,'605','Sueldos y Salarios e Ingresos Asimilados a Salarios', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(4,'606','Arrendamiento', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(5,'607','Régimen de Enajenación o Adquisición de Bienes', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(6,'608','Demás ingresos', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(7,'609','Consolidación', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(8,'610','Residentes en el Extranjero sin Establecimiento Permanente en México', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(9,'611','Ingresos por Dividendos (socios y accionistas)', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(10,'612','Personas Físicas con Actividades Empresariales y Profesionales', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(11,'614','Ingresos por intereses', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(12,'615','Régimen de los ingresos por obtención de premios', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(13,'616','Sin obligaciones fiscales', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(14,'620','Sociedades Cooperativas de Producat_sat_regimen_fiscalcción que optan por diferir sus ingresos', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(15,'621','Incorporación Fiscal', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(16,'622','Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(17,'623','Opcional para Grupos de Sociedades', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(18,'624','Coordinados', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(19,'625','Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(20,'626','Régimen Simplificado de Confianza', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(21,'628','Hidrocarburos', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(22,'629','De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales', now(), now(), null);
INSERT INTO cat_sat_regimen_fiscal VALUES(23,'630','Enajenación de acciones en bolsa de valores', now(), now(), null);