INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('01', 'Efectivo');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('02', 'Cheque nominativo');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('03', 'Transferencia electrónica de fondos');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('04', 'Tarjeta de crédito');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('05', 'Monedero electrónico');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('06', 'Dinero electrónico');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('08', 'Vales de despensa');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('12', 'Dación en pago');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('13', 'Pago por subrogación');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('14', 'Pago por consignación');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('15', 'Condonación');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('17', 'Compensación');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('23', 'Novación');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('24', 'Confusión');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('25', 'Remisión de deuda');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('26', 'Prescripción o caducidad');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('27', 'A satisfacción del acreedor');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('28', 'Tarjeta de débito');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('29', 'Tarjeta de servicios');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('30', 'Aplicación de anticipos');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('31', 'Intermediario pagos');
INSERT INTO cat_sat_forma_pago (codigo, nombre) VALUES('99', 'Por definir');
